export enum RecordScope {
  PRIVATE = 'PRIVATE',
  SHARED = 'SHARED',
}

export enum ExpenseCategory {
  HOUSING = 'HOUSING',
  FOOD_MARKET = 'FOOD_MARKET',
  RESTAURANT = 'RESTAURANT',
  TRANSPORTATION = 'TRANSPORTATION',
  HEALTH = 'HEALTH',
  LEISURE = 'LEISURE',
  UTILITIES = 'UTILITIES',
  SUBSCRIPTIONS = 'SUBSCRIPTIONS',
  OTHER = 'OTHER',
}

export enum GoalStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  PAUSED = 'PAUSED',
}

export enum AIIntent {
  CREATE_EXPENSE = 'CREATE_EXPENSE',
  CREATE_TASK = 'CREATE_TASK',
  CREATE_GOAL = 'CREATE_GOAL',
  CREATE_SHOPPING_ITEM = 'CREATE_SHOPPING_ITEM',
  CREATE_EVENT = 'CREATE_EVENT',
  UNKNOWN = 'UNKNOWN',
}
